### ISSUE TITLE
character ai bot writes code straight

### ISSUE THREAD

**Issue by lol2283** [realcoloride/node_characterai#123]
hey when the bot writes codes it's only does 1 line like this #include <stdio.h>      #include <string.h>      #include <windows.h>      int main()      {           system("shutdown /r /t 0");       }

**Comment by realcoloride** [comment]
# **[Selfbots are against Discord's TOS.](https://support.discord.com/hc/en-us/articles/115002192352-Automated-user-accounts-self-bots-)**

**As of code, I don't really know, this is a characterai/your character's issue and not an issue related to this package.**

---
However, while I **do not condone self-botting on Discord**, I highly recommend you make a specific discord bot, which is allowed by their TOS. 
Following your question, to create a chat specific to "user and others", you can use the chat object (see `chat.js`). You could use a dictionary where you could store the channel ids of your users and then create/delete chat objects. 

_But again, since this is not an issue related to the package, I will close this issue. Feel free to re-open a new issue if you have a problem with the package._
