### ISSUE TITLE
Client.createOrContinueChat() doesn't return anything.

### ISSUE THREAD

**Issue by Hadestia** [realcoloride/node_characterai#152]
Im using version 1.2.5 or later but This function doesn't seems to return any function after authentication. I waited for several minutes assuming the process is just slower than expected but it seems stuck in it. 

Here's my code below, I tried to check if it really returns anything using `console.dir()` but my terminal just ended on the same output.
![Screenshot_20240222-104756_1](https://github.com/realcoloride/node_characterai/assets/89353591/95ec1449-124e-476b-80c5-d3f748be8660)
![Screenshot_20240222-104729_1](https://github.com/realcoloride/node_characterai/assets/89353591/37b3f66f-b2fa-4ce4-8461-570efbda7c37)

**Comment by realcoloride** [comment]
Hello, why would you use console.dir?

**Comment by Hadestia** [comment]
> Hello, why would you use console.dir?

I just want to check if it really returns something, but it doesn't change the fact that my process ended only at authentication phase.

**Comment by realcoloride** [comment]
Hello again,

Make sure you dont create multiple characterAI clients for no reason. You can create multiple chats from one client.
Aswell, use console.log instead of console.dir.

If errors still happen, try to set node_characterai in `headful` mode, and investigate what the browser is showing up, if something is blocking your way.
