### ISSUE TITLE
Error: Could not get the full reply because it was aborted. This happens often when the output was filtered for violent or explicit content.

### ISSUE THREAD

**Issue by ToxiPain** [realcoloride/node_characterai#179]
I've had that error while using the API in my bot. I haven't sent anything bad or anything like that, it just came out and it doesn't change even that I put a new AI character... why is that?

Error: Could not get the full reply because it was aborted. This happens often when the output was filtered for violent or explicit content.

**Comment by realcoloride** [comment]
Hey there! 

This means like said that the output got filtered and aborted. Double check your character's prompt/description or messages.

It is the equivalent of having this:
![image](https://github.com/user-attachments/assets/28a8ac25-76b5-4fac-ae3d-8db7ffd6563e)

**Comment by ToxiPain** [comment]
But it continues to appear even when I change the character to another with diferent ID, I also tried to change the token, by any chance is there no file saved that causes the error ??
Because i tried to reinstall all and it doesnt work 

By the way, thank you very much for trying to help and answer quickly!

**Comment by Topandhi** [comment]
same here, its happen today,
yesterday it work fine

**Comment by Topandhi** [comment]
then when i check on c.ai website,
messages already there, but i dont get response from the api

**Comment by Topandhi** [comment]
Bug Report: API Response Error and Chat History Discrepancy
Description:
When using the API to chat with the bot, the chat history is correctly updated on the website, but no response is received through the API.

Steps to Reproduce:
Initiate a chat with the bot using the provided API.
Check the chat history on the website to confirm the chat is updated.
Observe that no response is received via the API.
Expected Behavior:
The API should return the bot's response along with updating the chat history on the website.
Actual Behavior:
The chat history is updated on the website, but no response is received from the API.
Screenshots:
Before Chat:
![AFTER CHAT](https://github.com/user-attachments/assets/8425e2ae-f489-45bc-b28c-0605896a042a)

After Chat:
![BEFORE CHAT](https://github.com/user-attachments/assets/9f12f21a-bba5-489a-a31e-7dca3efabb8e)


Error Message:
![DC](https://github.com/user-attachments/assets/df31ef7e-5927-452d-9f50-495f74b24321)


Additional Information:
The chat history is correctly displayed and updated on the website.
No response is received from the API endpoint.

Steps to Reproduce:
1.Take a screenshot of the chat history on the website.
2.Initiate a chat with the bot integrated with the nodecharacter_ai API.
3.Encounter the error message shown in the screenshot and receive a response indicating violent or explicit content.
4.Take a screenshot of the updated chat history on the website, confirming it is updated despite the error.

Expected Behavior:
The API should return the bot's response along with updating the chat history on the website.

Actual Behavior:
The chat history is updated on the website, but no response is received from the API, and an error message is displayed.

**Comment by Topandhi** [comment]
I added a log to the chat.js file:
![log](https://github.com/user-attachments/assets/a5402ca1-d31e-44f6-8825-93badfd04758)

I got this error: "No eligible candidates"
![error response](https://github.com/user-attachments/assets/cfd98444-8a76-4dbd-a72f-86bbe3da1d69)

**Comment by gamersindo1223** [comment]
Tried using an old chat looks like the /conversation endpoint cannot be used anymore

**Comment by gamersindo1223** [comment]
https://old.character.ai/chat?char=8_1NyR8w1dOXmI1uWaieQcd147hecbdIK7CeEAIrdJw&source=recent-chats

**Comment by realcoloride** [comment]
No eligible candidates? Oh no.. Perhaps they've changed the endpoints again. I'll investigate ASAP.

**Comment by fractalpublic** [comment]
Same problem here. Of course they change the endpoints the exact day I start using this.

**Comment by gamersindo1223** [comment]
looks like you can only chat using ws connection only

**Comment by gamersindo1223** [comment]
![image](https://github.com/user-attachments/assets/0bf296ea-cbb9-434e-b54f-0eec9f5c2e73)
it started to work again.

**Comment by Topandhi** [comment]
check it again, and it work fine

**Comment by realcoloride** [comment]
Hello again, is it working? It seems to be working fine for me

**Comment by gamersindo1223** [comment]
Yeah It's working
