### ISSUE TITLE
The Auth System may have changed again

### ISSUE THREAD

**Issue by ameshkin** [realcoloride/node_characterai#185]
I'm having issues getting it to work, signed in as a guest. I can't seem to find char_id in localstorage any more.

[node_characterai] Puppeteer - Warning: Guest users can only send up to 10 messages.
[node_characterai] Puppeteer - This is an experimental feature. Please report any issues on github.
[node_characterai] Puppeteer - Done with setup
[node_characterai] Puppeteer - Eval-fetching is an experimental feature and may be slower. Please report any issues on github
ai.user.username undefined
Error in CharacterAI handler: TypeError: Cannot read properties of undefined (reading 'user')

**Comment by realcoloride** [comment]
**Hello there, guests are now a deprecated feature from the old character ai interface, that was completely shut down September 24th, 2024, the [linked article is here](https://support.character.ai/hc/en-us/articles/28987281244827-The-old-beta-has-been-fully-retired-Please-use-character-ai-or-the-mobile-app).** 
The 2.0 update will get rid of guest mode completely.

To find your authorization token, see the cookies `HTTP_AUTHORIZATION` key or [click here](https://github.com/realcoloride/node_characterai/issues/146#issuecomment-2440173757)

As of currently, you can only log in to node_characterai with a token. I apologize for any issues caused, but it is out of my control.

The issue https://github.com/realcoloride/node_characterai/issues/180#issue-2424141450 covers the 2.0 roadmap, or the "neo" (new) interface.

Cheers

**Comment by ameshkin** [comment]
Thank you for helping. I would love to contribute to this project, however, I'm limited to what I can do since there is no public API for reference.  I would love to show you something that I am working on using this package.

**Comment by realcoloride** [comment]
**Thank you for showing your interest and support!** Feel free to contact me and show me what you are working on, I'd love to see it.

Yes working with the constantly changing infrastructure and new endpoints is pretty hard and tedious to do. The website is extremely unreliable that I have to remotely work with my laptop, and the rest of the endpoints are through the Android app, and I (literally) use very obscure android devices in order to proxy up and get all the requests and be able to make this work. Seriously, I did NOT know how hard it was to inspect traffic and work on it.

I don't have all the time I wish for to work on this but I am still actively working actively on it. Most of the endpoints have to be figured out by yourself because the android endpoints differ from the PC ones and they don't have Cloudflare limitations and have much more features.

> Is there a way to disconnect the chromium instances that are made? They just stay open until they are closed.

Processes should removed by default automatically and you shouldn't have to disconnect them by hand normally. 

Know that on the new endpoint, I am actively working on the websocket support and ditch chromium/puppeteer completely for the android endpoints, which can be risky, but the entire codebase restructure makes it better for that use case, I've also been focused on strongly typing out everything, but that means I have to test all requests individually and adapt per response case.

Almost NOTHING in the CharacterAI's new (neo) is NOT constant. Responses are almost all different. The API infrastructure is extremely strange and needs a LOT of manual work.

Cheers
