### ISSUE TITLE
chat is undefined

### ISSUE THREAD

**Issue by AzzaDeveloper** [realcoloride/node_characterai#2]
It's as straightforward as the title says.
Here's the code I used to test:
```
const CharacterAI = require('node_characterai');
const characterAI = new CharacterAI();
(async () => {
                    await characterAI.authenticateAsGuest();
                    const chat = await characterAI.createOrContinueChat("qvYZ0WMhydAFcefkmZDknc_7u4gKx6V0iBgP-aBmC6w");
})()
```
The issue persists no matter what CharacterID I use.

**Comment by AzzaDeveloper** [comment]
Not sure if it's worth noting but node throws a warning from the package everytime I run the app:
`(node:1568) ExperimentalWarning: The Fetch API is an experimental feature. This feature could change at any time`

**Comment by AzzaDeveloper** [comment]
Works perfectly when I use a token to authenticate!

**Comment by realcoloride** [comment]
Hello there!

Glad it worked for you when using a token to authenticate but what was the full error exactly? If it worked only when authenticating with a token it may mean that something is wrong with guest authentication.

I am currently not able to perform the test on myself and I can't bring much detail for now, but if it comes out as a bug, I will try to hunt it down and fix. 
In the meantime, try again and send me the sample code.

Also, the reason why you are getting the fetch warning in the console is because I use node-fetch to make the requests. It's a lightweight library but spits out this warning when doing anything with it. Sorry about that!

Though there may be tutorials about how to disable that I guess. 

I'll update you as soon as I can. If you have any other questions please let me know!

**Comment by zemzheng** [comment]
![image](https://user-images.githubusercontent.com/650956/220076660-05ba060f-300f-42ec-b250-6e1ff34e2b53.png)

**Comment by eliangerard** [comment]
I have the same problem, chat is undefined, it happens using the example code authenticating as guest:
![image](https://user-images.githubusercontent.com/72888646/220131231-79c9f4b2-fdeb-4b48-9ade-ed4ff9832eb4.png)

**Comment by realcoloride** [comment]
Alright.

Thanks for letting me know, I will investigate this as soon as I can.

In the meantime, please use an account to authenticate if you cannot login
with a guest token.

If you have any other questions or issues please let me know!

Le lun. 20 févr. 2023 à 15:18, Elian Gerard ***@***.***> a
écrit :

**Comment by SmartManoj** [comment]
Fails even with the token

```/home/smart/node_modules/node_characterai/client.js:126
        if (!this.isAuthenticated()) throw Error('You must be authenticated to do this.');
                                           ^

Error: You must be authenticated to do this.
    at Client.createOrContinueChat (/home/smart/node_modules/node_characterai/client.js:126:44)
    at /home/smart/Desktop/j.js:11:36
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v19.4.0``

**Comment by realcoloride** [comment]
That means your token is probably invalid

**Comment by realcoloride** [comment]
Hello everyone! Problem has been fixed.

CharacterAI's api had changed the status text "No Such History" to "there is no history between user and character", and outputing a 404.

Thus I fixed it now and added measures to go around that. 
![Code_GuceESIYP8](https://user-images.githubusercontent.com/108619637/220387757-fd892908-529f-4bbc-ac76-9d68fe502958.png)

**Remember that guest tokens only have a limited amount of messages!**

Pushed a new version, so go ahead and update to the latest one and tell me how it goes.

Have fun!

**Comment by cshadd** [comment]
Hi, the changes you made create this error for me

![image](https://user-images.githubusercontent.com/11986547/220459481-862466e1-7966-44ee-957e-cbcda701011d.png)

I am using this in a Typescript Project so I am not sure if this is because of the lack of Typescript definitions.

**Comment by eliangerard** [comment]
I have the same issue. I found out that it only happens when you try to create a chat with a character you've already had a chat with. So, if you only use the sendAndAwaitResponse method without creating a new chat every time, you'll be able to chat. If you switch to a different character and create a new chat, there won't be any problem. However, if you want to return to the chat with a character you've already talked to, it will crash.

This is the code that I'm using to evade the problem

![image](https://user-images.githubusercontent.com/72888646/220506975-1722b1ac-2837-4ab9-9995-9d855decd873.png)


And this is a capture of it not working

![image](https://user-images.githubusercontent.com/72888646/220506676-f9cc7956-f581-4f7c-ae8f-61a889898035.png)

**Comment by realcoloride** [comment]
Hello!

Thanks for the feedback and bug report. I think they changed the response
when the conversation already exists. I will investigate the issue and try
to fix it.

Sorry for the bugs and issues!

I will keep you updated.
Expect another bugfix update today.

Le mer. 22 févr. 2023 à 03:41, Elian Gerard ***@***.***> a
écrit :

**Comment by realcoloride** [comment]
Hello again!

The bug is fixed. It was simply due to a mistake from my end because I converted the response to text to retrieve the "no history between character...". I had forgotten to put it back to JSON after that.

![Code_ypeIJtaXqr](https://user-images.githubusercontent.com/108619637/220624616-6678db96-a2a4-4719-9291-2d8c156c8c92.png)

All issues should be resolved. Update to the latest version `1.0.19`.
If again you have any questions or have anything to report to me, feel free to do so!

Have fun.

**Comment by AzzaDeveloper** [comment]
Thank you so much for your work!
